# Generated by Django 3.2.9 on 2021-11-09 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0002_client_salescontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['lastName'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
