# Generated by Django 3.2.9 on 2021-11-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('userteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['last_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employe',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userteam.team'),
        ),
    ]
