# Generated by Django 3.2.9 on 2021-11-09 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0002_event_supportcontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['eventDate'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
    ]
