# Generated by Django 3.2.9 on 2021-11-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['eventDate'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
